### ISSUE TITLE
Guzzle Causing Json Encoding Error When Message Body is too large

### ISSUE THREAD

**Issue by sokser** [sendgrid/sendgrid-php#148]
After hours of searching I found that the new version of sendgrid-php is returning a json error if the message body is too large. I kept getting the following error:
````
PHP Fatal error:  Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'Unable to parse response body into JSON: 4' in /home/Email/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Response.php:861
Stack trace:
#0 /home/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php(122): Guzzle\Http\Message\Response->json()
#1 /home/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php(101): SendGrid->postRequest('/api/mail.send....', Array)
#2 /home/Email/email.php(712): SendGrid->send(Object(SendGrid\Email))
#3 /home/Email/main.php(103): Email->generateEmail(Array, NULL)
#4 /home/Email/main.php(154): Main->run()
#5 {main}
  thrown in /home/Email/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Response.php on line 861

Fatal error: Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'Unable to parse response body into JSON: 4' in /home/Email/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Response.php:861
Stack trace:
#0 /home/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php(122): Guzzle\Http\Message\Response->json()
#1 /home/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php(101): SendGrid->postRequest('/api/mail.send....', Array)
#2 /home/Email/email.php(712): SendGrid->send(Object(SendGrid\Email))
#3 /home/Email/main.php(103): Email->generateEmail(Array, NULL)
#4 /home/Email/main.php(154): Main->run()
#5 {main}
  thrown in /home/Email/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Response.php on line 861
````
When editing /home/Email/vendor/sendgrid/sendgrid/lib/SendGrid.php to print out the response, the message actually was:
```
Guzzle\Http\Message\Response Object
(
    [body:protected] => Guzzle\Http\EntityBody Object
        (
            [contentEncoding:protected] => 
            [rewindFunction:protected] => 
            [stream:protected] => Resource id #190
            [size:protected] => 
            [cache:protected] => Array
                (
                    [wrapper_type] => PHP
                    [stream_type] => TEMP
                    [mode] => w+b
                    [unread_bytes] => 0
                    [seekable] => 1
                    [uri] => php://temp
                    [is_local] => 1
                    [is_readable] => 1
                    [is_writable] => 1
                )

            [customData:protected] => Array
                (
                )

        )

    [reasonPhrase:protected] => Request Entity Too Large
    [statusCode:protected] => 413
    [info:protected] => Array
        (
            [url] => https://api.sendgrid.com/api/mail.send.json
            [content_type] => text/html
            [http_code] => 413
            [header_size] => 158
            [request_size] => 183
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.116375
            [namelookup_time] => 0.001744
            [connect_time] => 0.022283
            [pretransfer_time] => 0.093488
            [size_upload] => 98304
            [size_download] => 192
            [speed_download] => 1649
            [speed_upload] => 844717
            [download_content_length] => 192
            [upload_content_length] => 32503066
            [starttransfer_time] => 0.093494
            [redirect_time] => 0
            [redirect_url] => 
            [primary_ip] => 184.173.190.227
            [certinfo] => Array
                (
                )

            [primary_port] => 443
            [local_ip] => 104.130.119.20
            [local_port] => 41533
        )

    [effectiveUrl:protected] => https://api.sendgrid.com/api/mail.send.json
    [headers:protected] => Guzzle\Http\Message\Header\HeaderCollection Object
        (
            [headers:protected] => Array
                (
                    [server] => Guzzle\Http\Message\Header Object
                        (
                            [values:protected] => Array
                                (
                                    [0] => nginx
                                )

                            [header:protected] => Server
                            [glue:protected] => ,
                        )

                    [date] => Guzzle\Http\Message\Header Object
                        (
                            [values:protected] => Array
                                (
                                    [0] => Fri, 08 May 2015 15:18:36 GMT
                                )

                            [header:protected] => Date
                            [glue:protected] => ,
                        )

                    [content-type] => Guzzle\Http\Message\Header Object
                        (
                            [values:protected] => Array
                                (
                                    [0] => text/html
                                )

                            [header:protected] => Content-Type
                            [glue:protected] => ,
                        )

                    [content-length] => Guzzle\Http\Message\Header Object
                        (
                            [values:protected] => Array
                                (
                                    [0] => 192
                                )

                            [header:protected] => Content-Length
                            [glue:protected] => ,
                        )

                    [connection] => Guzzle\Http\Message\Header Object
                        (
                            [values:protected] => Array
                                (
                                    [0] => close
                                )

                            [header:protected] => Connection
                            [glue:protected] => ,
                        )

                )

        )

    [headerFactory:protected] => Guzzle\Http\Message\Header\HeaderFactory Object
        (
            [mapping:protected] => Array
                (
                    [cache-control] => Guzzle\Http\Message\Header\CacheControl
                    [link] => Guzzle\Http\Message\Header\Link
                )

        )

    [params:protected] => Guzzle\Common\Collection Object
        (
            [data:protected] => Array
                (
                )

        )

    [protocol:protected] => HTTP
    [protocolVersion:protected] => 1.1
)
````
Decreasing the number of users in each email seemed to solve the problem. But sendgrid-php should properly encode this as json rather than killing the program.

**Comment by eddiezane** [comment]
Apologies for the time this cost you and thanks for the detailed report. Could you please share more about what you were sending that was too big? I want to reproduce it for a fix.

**Comment by sokser** [comment]
We are using the beta testing with Sendgrid's template engine. However due to limitations in the engine we generate much of the body of the email on our servers and send it to the sendgrid via substitutions. For example for a user account email which may include their recently favorited items, a new row is created for each item. So the messages can be quite large depending on the users being sent to.

**Comment by smith2martin** [comment]
Similar production issue here, although not with sendgrid-php. This particular email was to a single user with a body size of 6791 characters, using the sendgrid java lib, via the X-SMTPAPI, and the message was well-formed. Response from Sendgrid is "413 Request Entity Too Large".  Please advise as to the ETA of a fix and / or documentation on the maximum message size that Sendgrid can handle.

**Comment by smith2martin** [comment]
In my case this ended up truly being a size issue. There were indeed attachments, and they were indeed sufficiently large to put the total message size above the 19.5 meg threshold. Sorry bout that.

**Comment by sokser** [comment]
Just shooting in the dark, but my issue arose when the email was very small
(e.g. 50 users and a couple of MB), try removing the attachment and does
the email send?

**Comment by thinkingserious** [comment]
I've updated the README to reflect the email size limitation. Thanks for reporting this and thanks to all who chipped in on the answer!

Reference: https://github.com/sendgrid/sendgrid-php/commit/cc6faf3c4f21a94085774ada8191714a5c48dbfd
